-- SQL Schema for Supabase "tasks" table
-- Copy and paste this into the SQL Editor in your Supabase Dashboard

-- 1. Create the tasks table
CREATE TABLE IF NOT EXISTS tasks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  building TEXT NOT NULL DEFAULT 'Building 100',
  sub_header TEXT,
  company TEXT,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  progress INTEGER DEFAULT 0,
  dependencies TEXT DEFAULT '',
  parent_id BIGINT,
  row_index INTEGER,
  color TEXT DEFAULT '#3498db',
  notes TEXT,
  type TEXT NOT NULL DEFAULT 'task',
  symbol TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 2. Enable Row Level Security (RLS)
ALTER TABLE tasks ENABLE ROW LEVEL SECURITY;

-- 3. Create RLS Policies to allow full access (read, insert, update, delete)
-- Note: You can restrict these policies later if you want to add user authentication.
CREATE POLICY "Allow public read access" ON tasks FOR SELECT USING (true);
CREATE POLICY "Allow public insert access" ON tasks FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow public update access" ON tasks FOR UPDATE USING (true) WITH CHECK (true);
CREATE POLICY "Allow public delete access" ON tasks FOR DELETE USING (true);
